
CONNECT amaldass_db/amaldass123;


CREATE TABLE amaldass_db.AGRI (
DIST_CODE NUMBER,
YEAR NUMBER(4),
STATE_CODE NUMBER,
STATE_NAME VARCHAR2(50),
DIST_NAME VARCHAR2(50),
RICE_AREA_1000_HA NUMBER(10,2),
RICE_PRODUCTION_1000_TONS NUMBER(10,2),
RICE_YIELD_KG_PER_HA NUMBER(10,2),
WHEAT_AREA_1000_HA NUMBER(10,2),
WHEAT_PRODUCTION_1000_TONS NUMBER(10,2),
WHEAT_YIELD_KG_PER_HA NUMBER(10,2),
KHARIF_SORGHUM_AREA_1000_HA NUMBER(10,2),
KHARIF_SORGHUM_PRODUCTION_1000_TONS NUMBER(10,2),
KHARIF_SORGHUM_YIELD_KG_PER_HA NUMBER(10,2),
RABI_SORGHUM_AREA_1000_HA NUMBER(10,2),
RABI_SORGHUM_PRODUCTION_1000_TONS NUMBER(10,2),
RABI_SORGHUM_YIELD_KG_PER_HA NUMBER(10,2),
SORGHUM_AREA_1000_HA NUMBER(10,2),
SORGHUM_PRODUCTION_1000_TONS NUMBER(10,2),
SORGHUM_YIELD_KG_PER_HA NUMBER(10,2),
PEARL_MILLET_AREA_1000_HA NUMBER(10,2),
PEARL_MILLET_PRODUCTION_1000_TONS NUMBER(10,2),
PEARL_MILLET_YIELD_KG_PER_HA NUMBER(10,2),
MAIZE_AREA_1000_HA NUMBER(10,2),
MAIZE_PRODUCTION_1000_TONS NUMBER(10,2),
MAIZE_YIELD_KG_PER_HA NUMBER(10,2),
FINGER_MILLET_AREA_1000_HA NUMBER(10,2),
FINGER_MILLET_PRODUCTION_1000_TONS NUMBER(10,2),
FINGER_MILLET_YIELD_KG_PER_HA NUMBER(10,2),
BARLEY_AREA_1000_HA NUMBER(10,2),
BARLEY_PRODUCTION_1000_TONS NUMBER(10,2),
BARLEY_YIELD_KG_PER_HA NUMBER(10,2),
CHICKPEA_AREA_1000_HA NUMBER(10,2),
CHICKPEA_PRODUCTION_1000_TONS NUMBER(10,2),
CHICKPEA_YIELD_KG_PER_HA NUMBER(10,2),
PIGEONPEA_AREA_1000_HA NUMBER(10,2),
PIGEONPEA_PRODUCTION_1000_TONS NUMBER(10,2),
PIGEONPEA_YIELD_KG_PER_HA NUMBER(10,2),
MINOR_PULSES_AREA_1000_HA NUMBER(10,2),
MINOR_PULSES_PRODUCTION_1000_TONS NUMBER(10,2),
MINOR_PULSES_YIELD_KG_PER_HA NUMBER(10,2),
GROUNDNUT_AREA_1000_HA NUMBER(10,2),
GROUNDNUT_PRODUCTION_1000_TONS NUMBER(10,2),
GROUNDNUT_YIELD_KG_PER_HA NUMBER(10,2),
SESAMUM_AREA_1000_HA NUMBER(10,2),
SESAMUM_PRODUCTION_1000_TONS NUMBER(10,2),
SESAMUM_YIELD_KG_PER_HA NUMBER(10,2),
RAPESEED_AND_MUSTARD_AREA_1000_HA NUMBER(10,2),
RAPESEED_AND_MUSTARD_PRODUCTION_1000_TONS NUMBER(10,2),
RAPESEED_AND_MUSTARD_YIELD_KG_PER_HA NUMBER(10,2),
SAFFLOWER_AREA_1000_HA NUMBER(10,2),
SAFFLOWER_PRODUCTION_1000_TONS NUMBER(10,2),
SAFFLOWER_YIELD_KG_PER_HA NUMBER(10,2),
CASTOR_AREA_1000_HA NUMBER(10,2),
CASTOR_PRODUCTION_1000_TONS NUMBER(10,2),
CASTOR_YIELD_KG_PER_HA NUMBER(10,2),
LINSEED_AREA_1000_HA NUMBER(10,2),
LINSEED_PRODUCTION_1000_TONS NUMBER(10,2),
LINSEED_YIELD_KG_PER_HA NUMBER(10,2),
SUNFLOWER_AREA_1000_HA NUMBER(10,2),
SUNFLOWER_PRODUCTION_1000_TONS NUMBER(10,2),
SUNFLOWER_YIELD_KG_PER_HA NUMBER(10,2),
SOYABEAN_AREA_1000_HA NUMBER(10,2),
SOYABEAN_PRODUCTION_1000_TONS NUMBER(10,2),
SOYABEAN_YIELD_KG_PER_HA NUMBER(10,2),
OILSEEDS_AREA_1000_HA NUMBER(10,2),
OILSEEDS_PRODUCTION_1000_TONS NUMBER(10,2),
OILSEEDS_YIELD_KG_PER_HA NUMBER(10,2),
SUGARCANE_AREA_1000_HA NUMBER(10,2),
SUGARCANE_PRODUCTION_1000_TONS NUMBER(10,2),
SUGARCANE_YIELD_KG_PER_HA NUMBER(10,2),
COTTON_AREA_1000_HA NUMBER(10,2),
COTTON_PRODUCTION_1000_TONS NUMBER(10,2),
COTTON_YIELD_KG_PER_HA NUMBER(10,2),
FRUITS_AREA_1000_HA NUMBER(10,2),
VEGETABLES_AREA_1000_HA NUMBER(10,2),
FRUITS_AND_VEGETABLES_AREA_1000_HA NUMBER(10,2),
POTATOES_AREA_1000_HA NUMBER(10,2),
ONION_AREA_1000_HA NUMBER(10,2),
FODDER_AREA_1000_HA NUMBER(10,2)
);

SHOW TABLES;
SELECT * FROM AGRI;

/*1. Year-wise Trend of Rice Production Across States (Top 3 States)*/

WITH top_states AS (
    SELECT STATE_NAME
    FROM AGRI
    GROUP BY STATE_NAME
    ORDER BY SUM(RICE_PRODUCTION_1000_TONS) DESC
    FETCH FIRST 3 ROWS ONLY
)
SELECT 
    YEAR,
    STATE_NAME,
    SUM(RICE_PRODUCTION_1000_TONS) AS RICE_PRODUCTION
FROM AGRI
WHERE STATE_NAME IN (SELECT STATE_NAME FROM top_states)
GROUP BY YEAR, STATE_NAME
ORDER BY YEAR, STATE_NAME;


/*2. Top 5 Districts by Wheat Yield Increase Over the Last 5 Years8*/

WITH year_range AS (
    SELECT MAX(YEAR) AS max_year FROM AGRI
)
SELECT 
    DIST_NAME,
    MAX(WHEAT_YIELD_KG_PER_HA) - MIN(WHEAT_YIELD_KG_PER_HA) AS YIELD_INCREASE
FROM AGRI, year_range
WHERE YEAR BETWEEN max_year - 4 AND max_year
GROUP BY DIST_NAME
ORDER BY YIELD_INCREASE DESC
FETCH FIRST 5 ROWS ONLY;

/*3. States with the Highest Growth in Oilseed Production (5-Year Growth Rate)*/

WITH oilseed_data AS (
    SELECT 
        STATE_NAME,
        YEAR,
        NVL(GROUNDNUT_PRODUCTION_1000_TONS, 0) +
        NVL(SOYABEAN_PRODUCTION_1000_TONS, 0) +
        NVL(SUNFLOWER_PRODUCTION_1000_TONS, 0) AS OILSEED_PRODUCTION
    FROM AGRI
),
ranked_years AS (
    SELECT
        STATE_NAME,
        YEAR,
        OILSEED_PRODUCTION,
        FIRST_VALUE(OILSEED_PRODUCTION) OVER (
            PARTITION BY STATE_NAME
            ORDER BY YEAR
        ) AS earliest,
        FIRST_VALUE(OILSEED_PRODUCTION) OVER (
            PARTITION BY STATE_NAME
            ORDER BY YEAR DESC
        ) AS latest
    FROM oilseed_data
)
SELECT
    STATE_NAME,
    ROUND(
        ((latest - earliest) / earliest) * 100,
        2
    ) AS GROWTH_PERCENT
FROM ranked_years
WHERE earliest > 0      -- ✅ prevents ORA-01476
GROUP BY STATE_NAME, earliest, latest
ORDER BY GROWTH_PERCENT DESC;



/*4.District-wise Correlation Between Area and Production (Rice, Wheat, Maize)*/

SELECT 
    DIST_NAME,
    ROUND(CORR(RICE_AREA_1000_HA,  RICE_PRODUCTION_1000_TONS),  2) AS RICE,
    ROUND(CORR(WHEAT_AREA_1000_HA, WHEAT_PRODUCTION_1000_TONS), 2) AS WHEAT,
    ROUND(CORR(MAIZE_AREA_1000_HA, MAIZE_PRODUCTION_1000_TONS), 2) AS MAIZE
FROM AGRI
GROUP BY DIST_NAME;

/*5. Yearly Production Growth of Cotton in Top 5 Cotton Producing States   */

WITH top_cotton_states AS (
    SELECT STATE_NAME
    FROM AGRI
    GROUP BY STATE_NAME
    ORDER BY SUM(COTTON_PRODUCTION_1000_TONS) DESC
    FETCH FIRST 5 ROWS ONLY
)
SELECT 
    YEAR,
    STATE_NAME,
    SUM(COTTON_PRODUCTION_1000_TONS) AS COTTON_PRODUCTION
FROM AGRI
WHERE STATE_NAME IN (SELECT STATE_NAME FROM top_cotton_states)
GROUP BY YEAR, STATE_NAME
ORDER BY YEAR, STATE_NAME;

/*6. Districts with the Highest Groundnut Production in 2017*/

SELECT 
    DIST_NAME,
    SUM(GROUNDNUT_PRODUCTION_1000_TONS) AS GROUNDNUT_PRODUCTION
FROM AGRI
WHERE YEAR = 2017
GROUP BY DIST_NAME
ORDER BY GROUNDNUT_PRODUCTION DESC
FETCH FIRST 5 ROWS ONLY;

/*7. Annual Average Maize Yield Across All States*/
SELECT 
YEAR,
    AVG(MAIZE_YIELD_KG_PER_HA) AS AVG_MAIZE_YIELD
FROM AGRI
GROUP BY YEAR
ORDER BY YEAR;

/* 8.Total Area Cultivated for Oilseeds in Each State*/

SELECT 
    STATE_NAME,
    SUM(GROUNDNUT_AREA_1000_HA +
        SOYABEAN_AREA_1000_HA +
        SUNFLOWER_AREA_1000_HA) AS TOTAL_OILSEED_AREA
FROM AGRI
GROUP BY STATE_NAME
ORDER BY TOTAL_OILSEED_AREA DESC;

/* 9. Districts with the Highest Rice Yield*/
    SELECT 
        DIST_NAME,
        STATE_NAME,
        RICE_YIELD_KG_PER_HA AS MAX_RICE_YIELD
    FROM AGRI
    ORDER BY RICE_YIELD_KG_PER_HA DESC
    FETCH FIRST 10 ROWS ONLY;


/* 10. Compare Wheat vs Rice Production for Top 5 States Over 10 Years */

WITH top_states AS (
    SELECT STATE_NAME
    FROM AGRI
    GROUP BY STATE_NAME
    ORDER BY SUM(RICE_PRODUCTION_1000_TONS + WHEAT_PRODUCTION_1000_TONS) DESC
    FETCH FIRST 5 ROWS ONLY
)
SELECT 
    YEAR,
    STATE_NAME,
    SUM(RICE_PRODUCTION_1000_TONS) AS RICE_PRODUCTION,
    SUM(WHEAT_PRODUCTION_1000_TONS) AS WHEAT_PRODUCTION
FROM AGRI
WHERE STATE_NAME IN (SELECT STATE_NAME FROM top_states)
GROUP BY YEAR, STATE_NAME
ORDER BY YEAR, STATE_NAME;
